### PR TITLE
Deploy VMs with Pulumi 

### PR DESCRIPTION
**Pull request by OscartGiles**
~~See README for details.~~

~~Currently relies on file on my local machine to deploy as contains secrets - will find better solution soon.~~

## Summary
Deploy and manage VMs with [Pulumi](https://www.pulumi.com/)

- See [README](https://github.com/alan-turing-institute/QUIPP-pipeline/blob/ab66fd82a55bce60e912a9a7405a7bf915e0731a/infrastructure/README.md) for instructions

## Highlights
- Now renders cloud init config file
- Gets fileshare info automatically (no more secret files in .gitignore)
- Can add VMs and individually configure location and size
- Can remove VMs individually (no need to destroy everything)

## Remaining issues (for next PR)
- Need to install cuda drivers if on GPU machine (Could switch to DataScience Linux VM base image)
- No shared pulumi state - If I spin up VMs, only I can destroy them. Need to move to Azure blob storage backend.

## For discussion
- It takes a long time to install all Python and R dependencies (~30min). Mostly R because it builds a load of stuff from source. Possible solutions:
    - Create our own VM image
    - Use our [docker image](https://github.com/alan-turing-institute/QUIPP-pipeline/pull/55)

### CODE REVIEW

**Comment by OscartGiles** [comment]
## Useful links:

https://blog.zenggyu.com/en/post/2018-01-29/installing-r-r-packages-e-g-tidyverse-and-rstudio-on-ubuntu-linux/


https://stackoverflow.com/questions/16382647/remove-all-packages-that-do-not-come-with-r

**Comment by martintoreilly** [comment]
Did you really mean to .gitignore `vm_config.yaml`? This feels like a critical file to include in the repo as it would seem to be where all the VM configuration is defined. Does this contain secrets?

In the safe haven deploy scripts, we deploy an Azure key vault and create/retrieve secrets from there, patching placeholders in the cloud init yaml with secrets retrieved from the key vault if required. This means we don't need to keep any state not in the repo or any local secrets. We just need to be logged into Azure powershell using an account with access to the subscription.

Happy to pair on this.

**Comment by martintoreilly** [comment]
For the safe haven we also define an up to date batteries included VM image with R, python etc installed, which I think we should be able to re-use here. If you need a later R version than our last VM build, we may need to rebuild our VM image to grab the latest versions of things, but this is also scripted and takes a few hours.

**Comment by OscartGiles** [comment]
@martintoreilly - Completely agree, I stuck it in there as a quick hack to get some secrets onto the VM fast, but I will clean it up next week before merging the PR. 

The missing cloud-init script currently:
- Adds all users/ssh keys
- Mounts a file share
- Installs R version + QUiPP dependencies (needs to pull new image https://blog.zenggyu.com/en/post/2018-01-29/installing-r-r-packages-e-g-tidyverse-and-rstudio-on-ubuntu-linux/) 
- Installs Miniconda
- Creates Conda env with python 3.8 + QUiPP dependencies

I also need to make a few changes to the deployment script (reminder to self):
- VM names are created from a loop index. Which makes it hard to remove individual VMs.

My other plan was to either get a workflow with Azure Container Instances or set up a Kubernetes Cluster setup for the team to run jobs on.

The nice thing with Azure Kubernetes is they recently added autoscaling node pools with zero nodes. So you can run a very cheap VM to run the scheduler on, and then have the big (possibly GPU) machines autoscale from zero when you submit a job and scale back down to zero when its finished  - a game-changer for CleanAir/Odysseus because we don't need GPU boxes at night.

I had thought azure container instances might do the job but turns out GPU support isn't great at the moment (although seems like it's in the pipeline).

**Pull request merged**
