### PR TITLE
Feature/sgf

### PR DESCRIPTION
**Pull request by crangelsmith**
Plausible deniability pipeline. General steps:

- From the usual method json file create all the config files needed by the sgf package. 
- Prepare the dataset into only numerical categories expected by the software.
- Run the synthesis method, generate data.
- Extract data points that pass the privacy metrics set up in the json file. 

The CI is failing because it can't find the sgf executables (which need to be downloaded and compiled separately). We should decide how to fix this optimally.

### CODE REVIEW

**Comment by gmingas** [comment]
Can the make file download and compile the sgf exectuables? Or maybe do it in a python script if it is easier?

**Comment by crangelsmith** [comment]
> Can the make file download and compile the sgf exectuables? Or maybe do it in a python script if it is easier?

I think @ots22 had some particular views on this, I will let him comment.

**Comment by ots22** [comment]
> >     Can the make file download and compile the sgf exectuables? Or maybe do it in a python script if it is easier?
> 
> I think @ots22 had some particular views on this, I will let him comment.

I think we should treat sgf as with any other dependency - provide instructions or perhaps a convenience setup script, and ideally include it in the Docker image (perhaps the one @LouiseABowler was working on) but it feels beyond what the Makefile should do.

**Review by gmingas — APPROVED** [review]
Approved after code review and tests passed locally. The run-synth-pipeline CI script needs to be fixed (install cmake and use it to install sgf before the pipeline run).

**Pull request merged**
